/**
 * JImpulse - A Java port of impulse.
 * Copyright © 2020 Bithatch (tanktarta@gmail.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_bithatch_jimpulse_Impulse */

#ifndef _Included_uk_co_bithatch_jimpulse_Impulse
#define _Included_uk_co_bithatch_jimpulse_Impulse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_bithatch_jimpulse_Impulse
 * Method:    setSourceIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_co_bithatch_jimpulse_Impulse_setSourceIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_bithatch_jimpulse_Impulse
 * Method:    initImpulse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_bithatch_jimpulse_Impulse_initImpulse
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_bithatch_jimpulse_Impulse
 * Method:    getSnapshot
 * Signature: (Z)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uk_co_bithatch_jimpulse_Impulse_getSnapshot
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
