/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_bithatch_jimpulse_Impulse */

#ifndef _Included_uk_co_bithatch_jimpulse_Impulse
#define _Included_uk_co_bithatch_jimpulse_Impulse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_bithatch_jimpulse_Impulse
 * Method:    setSourceIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_co_bithatch_jimpulse_Impulse_setSourceIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_bithatch_jimpulse_Impulse
 * Method:    initImpulse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_bithatch_jimpulse_Impulse_initImpulse
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_bithatch_jimpulse_Impulse
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_bithatch_jimpulse_Impulse_stop
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_bithatch_jimpulse_Impulse
 * Method:    getSnapshot
 * Signature: (Z)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uk_co_bithatch_jimpulse_Impulse_getSnapshot
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
